In [3]:
import numpy as np

In [5]:
print(np)

<module 'numpy' from 'C:\\Users\\Dell\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\numpy\\__init__.py'>


In [1]:
print("Hello world")

Hello world


In [ ]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\Dell\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


The python package numpy, which stands for "numerical python".

In [7]:
l1=[1,2,3,4,5]
l1

[1, 2, 3, 4, 5]

In [8]:
x=np.array(l1)
x

array([1, 2, 3, 4, 5])

find the differnts between python list and numpy array

In [10]:
#crate a 1D 
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [11]:
x=np.random.rand(3)
print(x)

[0.01459563 0.20045337 0.6757539 ]


In [12]:
x=np.random.randint(1,10,3)
print(x)

[6 9 7]


In [14]:
#2D array
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
y=np.random.randint(5,16,(3,3))
print(y)

[[14 10 10]
 [11  9  9]
 [10  8 12]]


In [ ]:

a=np.zeros((3,4),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
a=np.ones((4,5),dtype=float)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
a=np.full((5,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [23]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
a=5*np.eye(4,5,dtype=int)
print(a)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]]


In [27]:
print("shape of array:",a.shape )

shape of array: (4, 5)


In [32]:
a.ndim

2

In [30]:
a.size

20

In [31]:
a.dtype

dtype('int64')

In [33]:
x.max()

np.int32(9)

In [34]:
x.argmax()

np.int64(1)

In [35]:
a.mean()

np.float64(1.0)

In [38]:
y=np.random.randint(4,10,(3,3))
print(y)

[[9 8 7]
 [5 4 6]
 [5 5 7]]


In [39]:
x=np.random.randint(4,10,(3,3))
y=np.random.randint(5,16,(3,3))
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x//y)

[[5 4 6]
 [5 5 6]
 [7 7 9]]
[[ 8  9 11]
 [13  7 11]
 [ 9  7 15]]
[[13 13 17]
 [18 12 17]
 [16 14 24]]
[[-3 -5 -5]
 [-8 -2 -5]
 [-2  0 -6]]
[[ 40  36  66]
 [ 65  35  66]
 [ 63  49 135]]
[[0 0 0]
 [0 0 0]
 [0 1 0]]


Indexing is the process of accessing a single element from a sequence using its position or index

slicing refers to the process of extracting a portion of an array or a subarray. it allways you to
Access specific element ot range of element in a numpy array

Q-2 give a diff between indexing and slicing

In [40]:
x

array([[5, 4, 6],
       [5, 5, 6],
       [7, 7, 9]], dtype=int32)

In [41]:
x[2]

array([7, 7, 9], dtype=int32)

In [42]:
x[-3]

array([5, 4, 6], dtype=int32)

In [43]:
y

array([[ 8,  9, 11],
       [13,  7, 11],
       [ 9,  7, 15]], dtype=int32)

In [44]:
y[2]

array([ 9,  7, 15], dtype=int32)

In [55]:
x=[1,5,16,22,2]
print(x)

[1, 5, 16, 22, 2]


In [53]:
x[2:5]

[16, 22, 2]

In [54]:
np.flip(x)

array([ 2, 22, 16,  5,  1])

Tutorial : 2 - Explore Pandas library to analyze  and manipulate data.

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 837.5 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/11.0 MB 1.1 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.0 MB 1.1 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/11.0 MB 1.4 MB/s eta 0:00:07
   ------ --------------------------------- 1.8/11.0 MB 1.4 MB/s eta 0:00:07
   ------- -------------------------------- 2.1/11.0 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.4/11.0 MB 1.5 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.0 MB 1.4 MB/s eta 0:00:06
   ----------- ---------


[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\Dell\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
# # Import numpy and pandas library.
# install pandas before importing it
# pip install pandas
import pandas as pd

pandas is a open-source library for real world data anlysis in python.tsbis bulid on top of numpy.

using pandas, data can be cleaned, transformed,manipulateed,and analyzed.

to get started with pandas, numpy and pandas needs to be imported.

The basic data structure of pandas are seeries and dataframe.

1. series object is a one dimensional array, It supports differnts data types like integer,float,string etc.

2. DataFrame
A dataframe in pandas is a two-dimensional, tabular data structure similer to a spreadsheet or sql table.

It consists of rows and colums, where:

Colums: Represnt indivisual records or entiers

rows: Represent 

In [4]:
s1 = pd.Series([10,20,30,40,50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [7]:
s2 = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
s2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [8]:
s1.values

array([10, 20, 30, 40, 50])

In [9]:
s2.values

array([10, 20, 30, 40, 50])

In [11]:
s2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [12]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
data=[{'Name':'Divya','marks':85},
      {'Name':'john','marks':90},
      {'Name':'alis','marks':78}]
f1=pd.DataFrame(data)
f1

Name  marks
0  Divya     85
1   john     90
2   alis     78

In [17]:
data

[{'Name': 'Divya', 'marks': 85},
 {'Name': 'john', 'marks': 90},
 {'Name': 'alis', 'marks': 78}]

In [18]:
f1

Name  marks
0  Divya     85
1   john     90
2   alis     78

In [19]:
print(f1)

    Name  marks
0  Divya     85
1   john     90
2   alis     78


In [20]:
type(data)

list

In [22]:
type(f1)

pandas.core.frame.DataFrame

In [38]:
data=pd.read_excel("Book1.xlsx")
data

Name Branch Division
0      NaN    NaN      NaN
1    Divya     CE        B
2  Prinsal     IT        B
3   Trupti     CE        A
4    Hetvi     CE        B
5   Yashvi     IT        A

In [37]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\Dell\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [41]:
data= pd.read_csv("Iris.csv")
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [44]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [45]:
data.index

RangeIndex(start=0, stop=150, step=1)

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [47]:
data.isna()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [48]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [54]:
cat = data['Species'].unique()

In [55]:
cat

array(['setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [53]:
data.replace("Iris-setosa","setosa",inplace=True  )

In [56]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0            setosa  
1            setosa  
2            setosa  
3            setosa  
4            setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [59]:
data[['SepalLengthCm']].head(10)

SepalLengthCm
0            5.1
1            4.9
2            4.7
3            4.6
4            5.0
5            5.4
6            4.6
7            5.0
8            4.4
9            4.9

In [60]:
data[['SepalLengthCm','SepalWidthCm']].head(10)

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6
5            5.4           3.9
6            4.6           3.4
7            5.0           3.4
8            4.4           2.9
9            4.9           3.1