TUTORIAL-1

In [3]:
#1)Import numpy library.
import numpy as np

In [ ]:
#2)Create 1D array with 5 elements.
arr= np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
#3)Create 1D array with 5 elements random value. (by default values between 0 to 1)
arr= np.random.rand(5)
arr

array([0.96984626, 0.21390037, 0.07106155, 0.70962753, 0.67907449])

In [7]:
#4)Generate random value from range 5 to 15 with 1D array size 10.
arr= np.random.randint(5,15, size=10)
arr


array([ 8, 11,  6, 12,  9,  5,  8, 13,  9,  7], dtype=int32)

In [4]:
#5)Create 2D array - 4 by 3 size.
arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
#6)Create 2D array with size 3 by 3. Elements values are random number(by default values between 0 to 1)
arr= np.random.rand(3,3)
arr


array([[0.66634142, 0.77537648, 0.774654  ],
       [0.25925587, 0.43544299, 0.36598549],
       [0.33750199, 0.07169076, 0.45230562]])

In [6]:
#7)Generate random value from range 5 to 15 with 2D array size 3 by 3.
arr= np.random.randint(5,15, size=(3,3))
arr

array([[12, 13, 11],
       [12, 14,  8],
       [ 8, 10,  6]], dtype=int32)

In [7]:
#8)Create 3D array with size 2 * 3 * 2.
arr= np.random.rand(2,3,2)
arr


array([[[0.65756508, 0.31405153],
        [0.14477932, 0.48738253],
        [0.31276876, 0.9170247 ]],

       [[0.07393462, 0.72387797],
        [0.8464148 , 0.45509474],
        [0.55061311, 0.30303654]]])

In [8]:
#9)Initialize 5 by 5 array with all values are zeros.
arr= np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#10)Initialize 5 by 5 array with all values are ones.
arr= np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#11)Initialize 5 by 5 array with all values are particular values(consider 4).
arr= np.full((5,5),4)
arr

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [11]:
#12)Create indentity matrix with all diagonal values are 1 and rest all values are zeros.
arr= np.eye(4)
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#13)Find out shape of array.
arr.shape


(4, 4)

In [13]:
#14)Find dimension of array.
arr.ndim


2

In [14]:
#15)Find no. of elements of from above any array.
arr.size


16

In [15]:
#16)Find type of array.
arr.dtype


dtype('float64')

In [16]:
#17)Find maximum value from array.
arr.max()


np.float64(1.0)

In [17]:
#18)Find minimum value from array.
arr.min()


np.float64(0.0)

In [18]:
#19)Find average (mean) values from array.
arr.mean()


np.float64(0.25)

In [19]:
#20)Find location of maximum value from array.
arr.argmax()


np.int64(0)

In [20]:
#21)Create two 2D array of size 3 by 3 and perform four basic mathematical operations.
arr1= np.random.randint(1,10,size=(3,3))
arr2= np.random.randint(1,10,size=(3,3))
add= arr1 + arr2
sub= arr1 - arr2
mul= arr1 * arr2
div= arr1 / arr2
arr1, arr2, add, sub, mul, div


(array([[2, 1, 8],
        [2, 6, 4],
        [2, 2, 5]], dtype=int32),
 array([[4, 8, 6],
        [5, 6, 9],
        [9, 2, 3]], dtype=int32),
 array([[ 6,  9, 14],
        [ 7, 12, 13],
        [11,  4,  8]], dtype=int32),
 array([[-2, -7,  2],
        [-3,  0, -5],
        [-7,  0,  2]], dtype=int32),
 array([[ 8,  8, 48],
        [10, 36, 36],
        [18,  4, 15]], dtype=int32),
 array([[0.5       , 0.125     , 1.33333333],
        [0.4       , 1.        , 0.44444444],
        [0.22222222, 1.        , 1.66666667]]))

In [21]:
#22)Print index 2 and -2 value for 1D array. (indexing).
arr= np.random.randint(1,20,size=10)
arr[2], arr[-2]


(np.int32(4), np.int32(12))

In [22]:
#23)Perform indexing operations with 2D array.
arr= np.random.randint(1,20,size=(4,4))
arr[1,2]  #indexing for row 1 and column 2
arr[2]    #indexing for row 2(all columns)
arr[:,3]  #indexing for all rows and column 3


array([ 6,  4, 14, 10], dtype=int32)

In [23]:
#24)Print value of index 2 to 5 (slicing)
arr[2:6]


array([[ 3, 15, 19, 14],
       [ 5, 13, 14, 10]], dtype=int32)

In [24]:
#25)Print from index 0 to 5 values
arr[0:6]


array([[18,  7,  1,  6],
       [10,  6, 18,  4],
       [ 3, 15, 19, 14],
       [ 5, 13, 14, 10]], dtype=int32)

In [25]:
#26)Print from index 5 to all
arr[5:]


array([], shape=(0, 4), dtype=int32)

In [26]:
#27)Reassign value for particular index.
arr[2]= 99
arr


array([[18,  7,  1,  6],
       [10,  6, 18,  4],
       [99, 99, 99, 99],
       [ 5, 13, 14, 10]], dtype=int32)

In [27]:
#28)Reassign value 100 to all elements.
arr[:] = 100
arr


array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]], dtype=int32)

In [28]:
#29)Extract elements from index 1 to 7 with a step of 2.
arr[1:8:2]


array([[100, 100, 100, 100],
       [100, 100, 100, 100]], dtype=int32)

In [29]:
#30)Print Reverse the array.
arr[::-1]


array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]], dtype=int32)